name: Build And Publish Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Enable corepack
        run: corepack enable
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: 'Do the build'
        run: yarn && yarn build
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Build site
        run: yarn build
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Checkout hosting branch snapshot
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages-snapshot
        continue-on-error: true